import React, {useState, useEFfect} from 'react';

function AboutMe () {

    return (
        <>
        <div>
        <div id="AboutMeProfilePic" >
          <img src='/DronePhoto/AboutMe.webp' height="200px" />
        </div>
        <div id="AboutMeContent" >
          <h1>About Me</h1>
          Im Jay. Im a California native living near San Francisco. I built this website with React.js as a passion project to show some of the things I am interested in. As a web developer, I have experience building full stack applications and work with both front end design as well as server systems and database management. I  own several drones and fly them anywhere and everywhere I can, its my main artistic and creative outlet. Anything else I should say? I'm a Tottenham Hotspurs fan, Go Coys! Id like to do something meaningful in this world, and thats something I still need to figure out. Drop me a message if you'd like to connect. I'd love to get coffee sometime.
        </div>
        <div >
          
        </div>
        <div>
        </div>
      </div>
        </>
    )
}

export default AboutMe;